---
title: "Mannitol transgene and salt stress - in plants."
author: "Jennifer Daly, Micaela Beckman"
date: "April 24, 2017"
output: html_document
---

```{r, message=FALSE, warning=F}
#Required libraries
library(affy)
library(limma)
library(RSQLite)
#Import data from sources
pd = read.AnnotatedDataFrame("samples.txt",header=TRUE,sep=",",row.names=1) 
mydata = ReadAffy(filenames=pd$filename,phenoData=pd,verbose=TRUE)
sampleNames(mydata)=row.names(pData(pd))
#Call functions to organize data
eset = rma(mydata)
expression_data = exprs(eset)
```
COL.U1 has multiple blobs on it's image check.

Histogram is not normal but we will normalize the data using eset.

```{r}
TS = paste(pd$genotype,pd$treatment,sep=".")
TS = factor(TS, levels= c("M6PR.U","M6PR.T","COL.U","COL.T"))
```

```{r}
exp_design = model.matrix(~0 + TS)
colnames(exp_design) = levels(TS)
exp_design
```

```{r}
fit=lmFit(eset,exp_design)
```

```{r}
cont.matrix= makeContrasts(
    M6PR.TvU = M6PR.U - M6PR.T,
    COL.UvT = COL.U - COL.T,
    M6PRvCOL.T = M6PR.T - COL.T,
    M6PRvCOL.U = M6PR.U - COL.U,
    levels = exp_design)
fit2 = contrasts.fit(fit,cont.matrix)
fit2 = eBayes(fit2)
```


```{r}
# lfc =1 for 2-fold changes
result = decideTests(fit2, p.value=0.05, lfc=1)

colnames = c("M6PR.TvU",	"COL.UvT",	"M6PRvCOL.T",	"M6PRvCOL.U")
rownames = c("upregulated", "downregulated")
upregulated = c(sum(result[,1]>0), sum(result[,2]>0), sum(result[,3]>0), sum(result[,4]>0))
downregulated = c(sum(result[,1]<0), sum(result[,2]<0), sum(result[,3]<0), sum(result[,4]<0))

resultsMatrix = matrix(c(upregulated, downregulated), nrow=2, dimnames=list(rownames, colnames))
barplot(as.matrix(resultsMatrix), legend = rownames, beside=TRUE)
```

(A) Pathways mainly affected by salt stress; 
(B) pathways mainly activated by the M6PR transgene; 
(C) pathways affected by both salt stress and the M6PR transgene.




Retrieve annotations
```{r}
f="ftp://ftp.arabidopsis.org/Microarrays/Affymetrix/affy_ATH1_array_elements-2010-12-20.txt" 
annots = read.delim(f, na.strings = "", fill=TRUE, header=T, sep="\t") 
annots=annots[,c(1,5,6)] #Save selected (columns 1,5,6) info in annots table
```


```{r}
N=dim(eset)[1] 
top.M6PR.TvU = topTable(fit2,coef=1,number=N,p.value=0.05) 
top.COL.UvT = topTable(fit2,coef=2,number=N,p.value=0.05) 
top.M6PRvCOL.T = topTable(fit2,coef=3,number=N,p.value=0.05) 
top.M6PRvCOL.U = topTable(fit2,coef=4,number=N,p.value=0.05)
```

```{r}
row.names(annots)=annots$array_element_name 
top.M6PR.TvU.merged=merge(annots,top.M6PR.TvU,by="row.names") 
top.COL.UvT.merged=merge(annots,top.COL.UvT,by="row.names") 
top.M6PRvCOL.T.merged=merge(annots,top.M6PRvCOL.T,by="row.names") 
top.M6PRvCOL.U.merged=merge(annots,top.M6PRvCOL.U,by="row.names")
```



